apiVersion: cloud.google.com/v1beta1
kind: BackendConfig
metadata:
  namespace: cdn-api
  name: backend-config2
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false
