variable "gcp_project_id" {}
variable "provider_region" {}
variable "vpc_name" {}
variable "vpc_subnet_name" {}
variable "subnet_region" {}
variable "ip_name" {}
variable "sql_machine_type" {}
variable "compute_region" {}
variable "compute_machine_type" {}
variable "compute_zone" {}
variable "first_instance" {}
variable "second_instance" {}
variable "compute_image" {}
variable "third_instance" {}
variable "dataset_id" {}
variable "bq_friendly_name" {}
variable "bq_location" {}
variable "bq_owner_email" {}
variable "bucket_name" {}
variable "bucket_location" {}
variable "bucket_class" {}
variable "first_firewall" {}
variable "second_firewall" {}
variable "target_second_sa" {}
variable "source_second_sa" {}
variable "third_firewall" {}
variable "third_network_tag" {}
variable "fourth_firewall" {}
variable "target_fourth_firewall_sa" {}
variable "source_fourth_firewall_sa" {}
variable "fifth_firewall" {}
variable "fifth_firewall_tag" {}
variable "sixth_firewall" {}
variable "sixth_firewall_tag" {}
variable "seventh_firewall" {}
variable "target_seventh_firewall_tag"{}
variable "source_seventh_firewall_tag" {}
variable "eight_firewall" {}
variable "target_eight_firewall_tag" {}
variable "shared_subnet" {}
variable "host_project" {}
variable "shared_vpc_name" {}
