variable "gcp_project_id" {}
variable "provider_region" {}
variable "vpc_name" {}
variable "vpc_subnet_name" {}
variable "subnet_region" {}
variable "ip_name" {}
variable "sql_machine_type" {}
variable "compute_region" {}
variable "compute_machine_type" {}
variable "compute_zone" {}
variable "first_instance" {}
variable "second_instance" {}
variable "compute_image" {}
variable "third_instance" {}
variable "dataset_id" {}
variable "bq_friendly_name" {}
variable "bq_location" {}
variable "bq_owner_email" {}
variable "bucket_name" {}
variable "bucket_location" {}
variable "bucket_class" {}
variable "first_firewall" {}
variable "second_firewall" {}
variable "target_second_sa" {}
variable "source_second_sa" {}
variable "third_firewall" {}
variable "third_network_tag" {}
variable "fourth_firewall" {}
variable "target_fourth_firewall_sa" {}
variable "source_fourth_firewall_sa" {}
variable "fifth_firewall" {}
variable "fifth_firewall_tag" {}
variable "sixth_firewall" {}
variable "sixth_firewall_tag" {}
variable "seventh_firewall" {}
variable "target_seventh_firewall_tag"{}
variable "source_seventh_firewall_tag" {}
variable "eight_firewall" {}
variable "target_eight_firewall_tag" {}
variable "shared_subnet" {}
variable "host_project" {}
variable "shared_vpc_name" {}
[suhas_vengilat@instance-1 ~]$ cat terraform.tfvars
gcp_project_id = "project-1-256305"
provider_region = "asia-east1"
vpc_name = "private-service-sql-network"
vpc_subnet_name = "private-sql-network-subnet"
subnet_region = "us-central1"
ip_name = "private-service-sql-ip-address"
sql_machine_type = "db-f1-micro"
compute_region = "asia-east1"
compute_machine_type = "n1-standard-1"
compute_zone = "asia-east1-c"
first_instance = "a-sql-vm"
second_instance = "a-2-sql-vm"
compute_image = "centos-7-v20190905"
third_instance = "a-sql-vm-3"
dataset_id = "bqdatasetidtwo"
bq_friendly_name = "friendlyid"
bq_location = "asia-east1"
bq_owner_email = "suhas.vengilat@cloudsmes.com"
bucket_name = "an-example-111223334333"
bucket_location = "asia-east1"
bucket_class = "REGIONAL"
first_firewall = "internal-network-allow"
second_firewall = "pestathome-bastionhost-pestathomead-tcp-3389-allow-rule"
target_second_sa = ["oa-tf-506@host-prj-249608.iam.gserviceaccount.com"]
source_second_sa = ["tf-ss-new@host-prj-249608.iam.gserviceaccount.com"]
third_firewall = "pestathome-openvpn-bastionhost-tcp-3389-allow-rule"
third_network_tag = ["bastionhost"]
fourth_firewall = "petsathome-bastionhost-infoshare-cc-engine-tcp-3389-allow-rule"
target_fourth_firewall_sa = ["tf-ss-new@host-prj-249608.iam.gserviceaccount.com"]
source_fourth_firewall_sa = ["host-prj-249608@appspot.gserviceaccount.com"]
fifth_firewall = "petsathome-petsathomeapp-petsathome-host-ad-ports"
fifth_firewall_tag = ["petsathomeactivedirectory-vm"]
sixth_firewall = "petsathome-petsathomeapp-petsathome-host-dns-ports"
sixth_firewall_tag = ["petsathomeactivedirectory-vm"]
seventh_firewall = "petsathome-rx-dbs-mssql-bastionhost-tcp-3389-allow-rule"
target_seventh_firewall_tag =  ["rx-petpad-restore-dbs-mssql"]
source_seventh_firewall_tag = ["bastionhost"]
eight_firewall = "petsathomeonevpn-tcp-443"
target_eight_firewall_tag = ["petsathomeonevpn-deployment"]
shared_subnet = "host-subnet-1"
host_project = "host-prj-249608"
shared_vpc_name = "host-vpc"
